### ISSUE TITLE
Can't set credentials

### ISSUE THREAD

**Issue by mamadaevv** [hapheus/n8n-nodes-fusionbrain#1]
There is no option to add credentials:
![image](https://github.com/user-attachments/assets/3cf9d264-cf92-4004-8163-b5606b55cdc4)

---
_n8n Version 1.47.3_

**Comment by hapheus** [comment]
Does this work with other nodes?
Basically, n8n ( independent of the module) should prompt you to select credentials or create new ones.

<img width="305" alt="image" src="https://github.com/user-attachments/assets/230f1ad4-7f52-44ba-8efa-80cc96822bd0">
<img width="346" alt="image" src="https://github.com/user-attachments/assets/427a7402-de6a-4b94-b1e7-764d1e2c4cc9">

When exactly is “No data” displayed? 
Is this displayed after you have clicked on the input field for the credentials?

**Comment by mamadaevv** [comment]
I don't know why, but everything works.
